# Generated by Django 4.1.2 on 2022-10-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('club', models.CharField(max_length=100, null=True, verbose_name='Club name')),
                ('name', models.TextField(null=True, verbose_name='Event Details')),
                ('day', models.DateField(verbose_name='Day of the event')),
                ('start_time', models.TimeField(verbose_name='Starting time')),
                ('end_time', models.TimeField(verbose_name='Final time')),
                ('venue', models.CharField(blank=True, default='TBA', max_length=100, null=True, verbose_name='Venue or link')),
                ('overlap', models.BooleanField(default=False, verbose_name='Allow overlaps')),
                ('event_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Event Id')),
                ('event_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Google Calender Event Link')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
    ]
