# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-27 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='notes',
        ),
        migrations.AddField(
            model_name='event',
            name='club',
            field=models.TextField(help_text='the name of your club', null=True, verbose_name='Club Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.TextField(help_text='Describe your event', null=True, verbose_name='Name fo the Event'),
        ),
    ]
