# Generated by Django 4.1.2 on 2022-10-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_description_alter_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Event Details'),
        ),
    ]
