# Generated by Django 4.1.2 on 2022-10-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_email_subscription_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='club_email',
            field=models.CharField(max_length=100, verbose_name='Club Email'),
        ),
    ]
