# Generated by Django 4.1.2 on 2022-10-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.EmailField(default='pc@students.iitmandi.ac.in', max_length=254),
            preserve_default=False,
        ),
    ]
