# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-27 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20190927_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='club',
        ),
    ]
