# Generated by Django 4.1.2 on 2022-10-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_club_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='id',
        ),
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
