# Generated by Django 4.1.2 on 2022-10-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_club_id_alter_club_email'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('club_email', 'student_email'), name='Unique pair'),
        ),
    ]
