# Generated by Django 2.2.5 on 2019-09-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20190928_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.CharField(blank=True, help_text='the name of your club', max_length=100, null=True, verbose_name='Club name'),
        ),
    ]
