# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-28 11:31
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20190928_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.CharField(default=django.contrib.auth.models.User, help_text='the name of your club', max_length=100, null=True, verbose_name='Club name'),
        ),
    ]
