# Generated by Django 2.2.6 on 2019-10-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20190928_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, default='TBA', help_text='Venue of the event', max_length=100, null=True, verbose_name='Venue'),
        ),
    ]
