# Generated by Django 2.2.6 on 2019-10-28 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2019, 10, 29, 23, 59, 21, 401550), help_text='Final time', verbose_name='Final time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2019, 10, 29, 0, 0, 21, 401597), help_text='Starting time', verbose_name='Starting time'),
        ),
    ]
