# Generated by Django 2.2.6 on 2019-10-28 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20191029_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2019, 10, 29, 23, 59, 8, 63592), help_text='Final time', verbose_name='Final time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2019, 10, 29, 0, 0, 8, 63604), help_text='Starting time', verbose_name='Starting time'),
        ),
    ]
