# Generated by Django 3.1.4 on 2021-01-02 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20191029_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.CharField(max_length=100, null=True, verbose_name='Club name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 3, 23, 59, 54, 762252), verbose_name='Final time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.TextField(null=True, verbose_name='Event Details'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 3, 0, 0, 54, 762252), verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, default='TBA', max_length=100, null=True, verbose_name='Venue'),
        ),
    ]
