# Generated by Django 3.1.4 on 2021-01-02 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20210103_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 3, 23, 59, 48, 759843), verbose_name='Final time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 3, 0, 0, 48, 759843), verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, default='TBA', max_length=100, null=True, verbose_name='Venue or link'),
        ),
    ]
